### ISSUE TITLE
pRNASeqTools not recognizing bowtie2 even when its installed

### ISSUE THREAD

**Issue by jnvinc0016** [grubbybio/pRNASeqTools#1]
I am trying to use pRNASeqTools to process sRNA-seq data. However, after installing pRNASeqTools and the required dependencies, pRNASeqTools is still requesting for bowtie2 to be installed.
![Screenshot from 2022-11-16 15-03-33](https://user-images.githubusercontent.com/118399209/202305937-926302e0-2255-4263-91fd-2f4a8f258bb7.png)
You can see from the above image that other dependencies have been installed, and while pRNASeqTools states to install bowtie2, there is no error message stating: "Can't exec "bowtie2": No such file or directory at precheck.pm line 15" as there is prior to package installation. 

![Screenshot from 2022-11-16 15-04-19](https://user-images.githubusercontent.com/118399209/202305939-1fe86645-bbbe-4481-9b3f-b57d2ea7a028.png)
Above is a screenshot showing that bowtie2 can be accessed from within the conda environment I made for pRNASeqTools. 

Any help would be greatly appreciated! Thanks in advance!

**Comment by grubbybio** [comment]
Hi there,

Thanks for your question. Please update the bowtie2 to the latest version. This issue is because recent versions of bowtie2 provide  different version info. Later I would update the install file or make changes in the pipeline to make older bowtie2 compatible.

Best,

Chenjiang You, Ph.D.
Young PI
School of Life Sciences, Fudan University
2005 Songhu Rd. Shanghai, China, 200438

**Comment by jnvinc0016** [comment]
Thank you for your response, Dr. You!

I was able to resolve the bowtie2 issue with your suggestion...however...I am not having another problem: pRNASeqTools is not picking up the "_genes.gff" file that is in the same folder as my data files (see attached image for reference). There is also an issue with some R packages, even though they are installed. I'm sure these are more silly issues on my end, as I'm not very familiar with Perl. Thanks in advance for your help!
![Screenshot from 2022-12-05 16-56-57](https://user-images.githubusercontent.com/118399209/205772423-0f5cf55f-81be-49a5-9926-c637862ec8d4.png)

**Comment by grubbybio** [comment]
Issue closed as problem solved
